# Introduction to Data Analysis with Pandas

[Pandas](https://pandas.pydata.org/) ist eine Library und der de-facto Industry Standart für die Datenanalyse in Python. Installiere Pandas in deinem Environment mit `pip install pandas`.

## Setup

In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("data/eurostat_european_cities.csv")
df_raw.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.50,0.0,3.5,1917.0,22.4,...,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.4,NaN,NaN
1,Antwerpen (greater city),5.0,17.6,4.2,759.8,NaN,0.0,19.0,NaN,28.4,...,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.8,49.00,15.0
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.0
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.0,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.0,63.42,17.3

## Data Inspection

Ein Pandas DataFrame ist eine tabellenartige Datenstruktur in Python, die Daten in Zeilen und Spalten organisiert.

In [3]:
type(df_raw)

pandas.core.frame.DataFrame

In [4]:
# spalten ausgeben
df_raw.columns

Index(['cities', 'cenv_Total number of hours of sunshine per day',
       'cenv_Average temperature of warmest month - degrees',
       'cenv_Average temperature of coldest month - degrees',
       'cenv_Rainfall - litre/m²',
       'cenv_Number of days ozone O3 concentrations exceed 120 µg/m³',
       'cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³',
       'cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³',
       'cenv_Accumulated ozone concentration in excess 70 µg/m³',
       'cenv_Annual average concentration of NO2 (µg/m³)',
       ...
       'ctran_Average length of journey to work by private car - km',
       'ctran_Number of registered cars per 1000 population',
       'ctran_Number of private cars registered',
       'ctran_People killed in road accidents per 10000 pop.',
       'ctran_Number of deaths in road accidents',
       'ctran_People commuting into the city',
       'ctran_People commuting out of the city',
       'ctran_Length of bicycle network (dedicated cycle paths and lanes) - km',
       'ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR',
       'ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR'],
      dtype='object', length=149)

In [5]:
# spalten als loop ausgeben
for col in df_raw.columns: 
    print(col)

cities
cenv_Total number of hours of sunshine per day
cenv_Average temperature of warmest month - degrees
cenv_Average temperature of coldest month - degrees
cenv_Rainfall - litre/m²
cenv_Number of days ozone O3 concentrations exceed 120 µg/m³
cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³
cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³
cenv_Accumulated ozone concentration in excess 70 µg/m³
cenv_Annual average concentration of NO2 (µg/m³)
cenv_Annual average concentration of PM10 (µg/m³)
cenv_Total use of water - m³
cenv_Price of a m³ of domestic water - Euro
cenv_Share of the urban wastewater load (in population equivalents) treated according to the applicable standard -%
cenv_Share of population connected to potable drinking water system - %
cenv_Share of population connected to sewerage treatment system - %
cenv_Municipal waste generated (domestic and commercial), total - 1000 t
cenv_Share of land (%): continuous residential urban fabric
cenv_Share of land (%): discontinuous residential urban fabric
cenv_Share of land (%): industrial, commercial, public, military and private units
cenv_Share of land (%): transport infrastructure
cenv_Share of land (%): other artificial areas
cenv_Share of land (%): green urban areas and sports and leisure facilities
cenv_Share of land (%): agricultural areas
cenv_Share of land (%): natural areas
clivcon_Private households (excluding institutional households)
clivcon_Proportion of households that are 1-person households
clivcon_One person households
clivcon_Average size of households
clivcon_Proportion of households that are lone-parent households
clivcon_Lone parent private households (with children aged 0 to under 18)
clivcon_Proportion of households that are lone-pensioner households
clivcon_Lone pensioner (above retirement age) households
clivcon_Proportion of households with children aged 0-17
clivcon_Households with children aged 0 to under 18
clivcon_Lone parent households per 100 households with children aged 0-17
clivcon_Population living in private households (excluding institutional households)
clivcon_Median disposable annual household income - EUR
clivcon_Average disposable annual household income - EUR
clivcon_Share of persons living in households with very low work intensity - %
clivcon_Share of persons at risk of poverty after social transfers -%
clivcon_Share of severely materially deprived persons -%
clivcon_Share of persons at risk of poverty or social exclusion -%
clivcon_Number of conventional dwellings
clivcon_Number of houses
clivcon_Number of apartments
clivcon_Proportion of households living in houses
clivcon_Number of households living in houses
clivcon_Proportion of households living in apartments
clivcon_Number of households living in apartments
clivcon_Proportion of households living in owned dwellings
clivcon_Households owning their own dwelling
clivcon_Households in social housing
clivcon_Households in private rented housing
clivcon_Dwellings lacking basic amenities
clivcon_Average area of living accommodation - m²/person
clivcon_Empty conventional dwellings
clivcon_Number of people in accommodation for the homeless
clivcon_Average annual rent for housing per m² - EUR
clivcon_Average price for buying a house - EUR
clivcon_Average price for buying an apartment - EUR
clivcon_Average price for buying a house per m2 - EUR
clivcon_Average price for buying an apartment per m2 - EUR
clivcon_Number of murders and violent deaths
clma_Activity rate
clma_Activity rate, male
clma_Economically active population, male
clma_Activity rate, female
clma_Economically active population, female
clma_Persons unemployed, total
clma_Unemployment rate, male
clma_Persons unemployed, male
clma_Unemployment rate, female
clma_Persons unemployed, female
clma_Unemployment rate
clma_Economically active population, 55-64, total
clma_Economically active population, 55-64, male
clma_Economically active population, 55-64, female
clma_Economically active population, 20-64, total
clma_Economically active population, 20-64, male
clma_Economically active population, 20-64, female
clma_Persons employed, 20-64, total
clma_Persons employed, 20-64, male
clma_Persons employed, 20-64, female
clma_Persons employed, 55-64, total
clma_Persons employed, 55-64, male
clma_Persons employed, 55-64, female
clma_Employment (jobs) in agriculture, fishery (NACE Rev. 2, A)
clma_Employment (jobs) in mining, manufacturing, energy (NACE Rev. 2, B-E)
clma_Total employment/jobs (workplace based)
clma_Employment (jobs) in construction (NACE Rev. 2, F)
clma_Employment (jobs) in trade, transport, hotels, restaurants (NACE Rev. 2, G to I)
clma_Employment (jobs) in information and communication (NACE Rev. 2, J)
clma_Employment (jobs) in financial and insurance activities (NACE Rev. 2, K)
clma_Employment (jobs) in real estate activities (NACE Rev. 2, L)
clma_Employment (jobs) in professional, scientific and technical activities; administrative and support service activities (NACE Rev. 2, M and N)
clma_Employment (jobs) in public administration, defence, education, human health and social work activities (NACE Rev. 2, O to Q)
clma_Employment (jobs) in arts, entertainment and recreation; other service activities; activities of household and extra-territorial organizations and bodies (NACE Rev. 2, R to T)
cpop1_Population on the 1st of January, total
cpop1_Population on the 1st of January, male
cpopcb_Nationals as a proportion of population
cpopcb_Nationals
cpopcb_EU foreigners as a proportion of population
cpopcb_EU foreigners
cpopcb_Non-EU foreigners as a proportion of population
cpopcb_Non-EU foreigners
cpopcb_Foreigners as a proportion of population
cpopcb_Native-born as a proportion of population
cpopcb_Native-born
cpopcb_Foreign-born as a proportion of population
cpopcb_Foreign-born
cpopcb_Foreign-born in a EU country
cpopcb_Foreign-born in a non-EU country
cpopcb_Foreigners
cpopcb_Population with the place of residence in the same dwelling, in the year before
cpopcb_Population with the place of residence in another dwelling in the same city/FUA, in the year before
cpopcb_Population with the place of residence in another dwelling outside the current city/FUA in the same country, in the year before
cpopcb_Population with the place of residence in another EU country, in the year before
cpopcb_Population with the place of residence outside the EU, in the year before
ctour_Number of cinema seats per 1000 residents
ctour_Number of cinema seats (total capacity)
ctour_Cinema attendance (per year)
ctour_Number of museum visitors (per year)
ctour_Number of theatres
ctour_Number of public libraries (all distribution points)
ctour_Number of public swimming pools (indoor and outdoor, excluding beaches)
ctour_Total nights spent in tourist accommodation establishments
ctour_Number of bed-places in tourist accommodation establishments
ctour_Number of available beds per 1000 residents
ctour_Nights spent in tourist accommodation establishments by residents
ctour_Total nights spent in tourist accommodation establishments per resident population
ctour_Nights spent in tourist accommodation establishments by non-residents
ctran_Share of journeys to work by car -%
ctran_Share of journeys to work by motorcycle -%
ctran_Share of journeys to work by bicycle -%
ctran_Share of journeys to work by foot -%
ctran_Share of journeys to work by public transport (rail, metro, bus, tram) -%
ctran_Share of journeys to work by car or motorcycle -%
ctran_Average time of journey to work - minutes
ctran_Average length of journey to work by private car - km
ctran_Number of registered cars per 1000 population
ctran_Number of private cars registered
ctran_People killed in road accidents per 10000 pop.
ctran_Number of deaths in road accidents
ctran_People commuting into the city
ctran_People commuting out of the city
ctran_Length of bicycle network (dedicated cycle paths and lanes) - km
ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR
ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR

In [6]:
# print the first 5 entries
df_raw.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.50,0.0,3.5,1917.0,22.4,...,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.4,NaN,NaN
1,Antwerpen (greater city),5.0,17.6,4.2,759.8,NaN,0.0,19.0,NaN,28.4,...,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.8,49.00,15.0
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.0
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.0,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.0,63.42,17.3

In [7]:
# print the last 5 entries
df_raw.tail()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
44,Warszawa,7.0,21.1,-1.0,519.0,9.0,0.0,40.5,3312.0,24.3,...,NaN,845.97,1574854.0,0.16,29.0,NaN,NaN,773.4,24.40,4.47
45,Wien (greater city),NaN,NaN,NaN,NaN,24.6,0.0,20.0,4775.0,20.8,...,NaN,NaN,NaN,0.12,21.0,NaN,NaN,NaN,NaN,NaN
46,Zagreb,NaN,NaN,NaN,NaN,3.0,0.0,39.0,NaN,35.0,...,NaN,390.42,296727.0,0.36,27.0,NaN,NaN,427.0,53.00,8.00
47,Zurich (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.28,407.99,294192.0,0.26,19.0,238202.43,62484.9,NaN,91.00,35.00
48,Łódź,5.0,20.1,-0.9,521.0,12.0,0.0,80.3,4102.0,22.6,...,NaN,681.02,444038.0,0.29,19.0,NaN,NaN,245.3,21.12,3.47

In [8]:
# change how many "top/tail" entries to display
df_raw.head(10)

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.50,0.00,3.5,1917.0,22.4,...,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.40,NaN,NaN
1,Antwerpen (greater city),5.0,17.6,4.2,759.8,NaN,0.00,19.0,NaN,28.4,...,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.80,49.00,15.00
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.00
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.00,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.00,63.42,17.30
5,Birmingham,NaN,NaN,NaN,NaN,3.50,0.00,7.0,1716.0,31.9,...,NaN,330.57,376607.0,0.12,14.0,NaN,NaN,233.00,102.67,NaN
6,Bratislava (greater city),NaN,NaN,NaN,NaN,28.00,1.00,13.5,4837.0,24.0,...,NaN,400.28,190336.0,0.16,7.0,141694.00,12931.00,122.06,26.90,4.59
7,Brno,NaN,NaN,NaN,NaN,19.00,0.00,20.0,3982.0,17.4,...,NaN,424.73,160959.0,0.21,8.0,55778.00,11467.00,39.00,21.87,7.16
8,Bruxelles/Brussel (greater city),5.0,17.6,4.0,815.7,10.33,1.25,14.7,2390.0,30.3,...,NaN,394.55,498855.0,0.09,11.0,NaN,NaN,513.00,60.00,15.00
9,Budapest (greater city),NaN,23.9,-1.0,815.2,21.00,0.00,26.0,3973.0,23.4,...,NaN,428.99,723372.0,0.23,38.0,NaN,NaN,213.00,22.65,7.59

In [9]:
# print/access an item on a specific location, index starts at 0!
df_raw.iloc[2]

cities                                                                                                           Barcelona (greater city)
cenv_Total number of hours of sunshine per day                                                                                        NaN
cenv_Average temperature of warmest month - degrees                                                                                   NaN
cenv_Average temperature of coldest month - degrees                                                                                   NaN
cenv_Rainfall - litre/m²                                                                                                              NaN
                                                                                                                           ...
ctran_People commuting into the city                                                                                                  NaN
ctran_People commuting out of the city                                                                                                NaN
ctran_Length of bicycle network (dedicated cycle paths and lanes) - km                                                                NaN
ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR                         NaN
ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR                                                                     NaN
Name: 2, Length: 149, dtype: object

In [10]:
# print/access a specific column, also helpful to get index numbers
df_raw["cities"]

0             Amsterdam (greater city)
1             Antwerpen (greater city)
2             Barcelona (greater city)
3                 Basel (greater city)
4                               Berlin
5                           Birmingham
6            Bratislava (greater city)
7                                 Brno
8     Bruxelles/Brussel (greater city)
9              Budapest (greater city)
10                 Cork (greater city)
11                            Debrecen
12               Dublin (greater city)
13               Geneva (greater city)
14                                Gent
15                             Glasgow
16                                Graz
17                             Hamburg
18               Košice (greater city)
19                              Kraków
20             Limerick (greater city)
21                 Linz (greater city)
22               Lisboa (greater city)
23                           Ljubljana
24                              London
25           Luxembourg (greater city)
26                 Lyon (greater city)
27               Madrid (greater city)
28                             Maribor
29            Marseille (greater city)
30               Milano (greater city)
31                             München
32               Napoli (greater city)
33                             Ostrava
34                Paris (greater city)
35                Porto (greater city)
36                               Praha
37                              Prešov
38                              Rijeka
39                                Roma
40            Rotterdam (greater city)
41                Split (greater city)
42                              Szeged
43             Valencia (greater city)
44                            Warszawa
45                 Wien (greater city)
46                              Zagreb
47               Zurich (greater city)
48                                Łódź
Name: cities, dtype: object

In [11]:
# generate a subset based on the index number, e.g. all cities with letter C
# Python slices are start inclusive, end exclusive, so 2:10 gives you rows 2 through 10.
c_cities = df_raw.iloc[2:10]
c_cities

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.00
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.00,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.00,63.42,17.30
5,Birmingham,NaN,NaN,NaN,NaN,3.50,0.00,7.0,1716.0,31.9,...,NaN,330.57,376607.0,0.12,14.0,NaN,NaN,233.00,102.67,NaN
6,Bratislava (greater city),NaN,NaN,NaN,NaN,28.00,1.00,13.5,4837.0,24.0,...,NaN,400.28,190336.0,0.16,7.0,141694.00,12931.00,122.06,26.90,4.59
7,Brno,NaN,NaN,NaN,NaN,19.00,0.00,20.0,3982.0,17.4,...,NaN,424.73,160959.0,0.21,8.0,55778.00,11467.00,39.00,21.87,7.16
8,Bruxelles/Brussel (greater city),5.0,17.6,4.0,815.7,10.33,1.25,14.7,2390.0,30.3,...,NaN,394.55,498855.0,0.09,11.0,NaN,NaN,513.00,60.00,15.00
9,Budapest (greater city),NaN,23.9,-1.0,815.2,21.00,0.00,26.0,3973.0,23.4,...,NaN,428.99,723372.0,0.23,38.0,NaN,NaN,213.00,22.65,7.59

## Basic Statistics

Pandas bietet eine ganze Reihe von eingebauten Funktionen um einfache und komplexe Statistiken zu einem Datensatz auszugeben, darunter `.mean()`, `.median()`, `,mode()`, `.min()` und `.max()`.

- Der Mittelwert (Mean) ist der Durchschnitt, der berechnet wird, indem alle Werte addiert und durch die Anzahl der Werte geteilt werden. 
- Der Median hingegen ist der mittlere Wert in einer sortierten Datenreihe, der die Daten in zwei Hälften teilt – unabhängig von extremen Ausreißern. Sollte es sich um eine gerade Anzahl von Werten handeln so ist der Median das Mittel der beiden mittleren Werte. 
- Mode bezeichnet den häufigsten Wert in einer Zahlenreihe. Es kann auch mehrere Modalwerte geben wenn mehrere Zahlen gleich häufig vorkommen. 
- Min. und Max. bezeichnen den niedrigsten, bzw. höchsten Wert in einer sortierten oder unsortierten Zahlenreihe.

### Describe

Standardmäßig zeigt Pandas bei DataFrame.describe() sehr viele Nachkommastellen oder wissenschaftliche Notation (1.234567e+06) an. Das kann unübersichtlich wirken – besonders, wenn man die Zahlen nur überblicken und nicht hochpräzise weiterverarbeiten möchte. Über folgenden command kannst du alle Fließkommazahlen mit genau zwei Nachkommastellen anzeigen. Dadurch wird der Vergleich zwischen Spalten einfacher.

In [12]:
# .describe() outputs all popular statistics of a data set.
# Disable scientific notation for floats
pd.set_option('display.float_format', '{:.3f}'.format)
summary = df_raw.describe()

summary

,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),cenv_Annual average concentration of PM10 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
count,8.000,12.000,12.000,12.000,31.000,33.000,33.000,30.000,33.000,32.000,...,14.000,40.000,43.000,45.000,48.000,25.000,25.000,33.000,30.000,33.000
mean,5.338,19.925,0.583,728.167,13.876,0.158,23.982,3357.867,26.945,24.984,...,15.351,434.050,628999.116,0.219,28.062,252449.684,133194.663,68501.732,45.553,11.010
std,0.769,2.363,2.331,143.413,10.234,0.494,25.739,1512.010,6.095,6.989,...,5.610,131.271,788847.514,0.114,37.192,248002.375,178123.368,230417.150,24.954,7.116
min,4.500,17.200,-1.700,519.000,0.000,0.000,1.000,265.000,12.400,13.300,...,10.300,278.970,21369.000,0.070,1.000,15213.000,6182.000,0.000,16.600,3.470
25%,5.000,17.600,-1.075,606.275,4.000,0.000,7.000,1998.500,22.700,20.750,...,11.438,353.530,125085.000,0.130,8.000,53553.000,12931.000,79.000,23.060,6.580
50%,5.000,20.050,-0.700,754.750,14.000,0.000,20.000,3450.000,27.300,24.200,...,12.550,400.340,376607.000,0.180,15.500,212389.000,62484.900,245.300,42.500,9.000
75%,5.500,21.450,2.050,821.175,21.000,0.000,26.000,4480.250,31.500,26.775,...,18.320,450.430,658490.000,0.290,30.000,321219.000,186104.000,513.000,60.000,15.000
max,7.000,23.900,4.200,972.300,38.270,2.400,121.000,5779.000,38.500,46.800,...,27.000,845.970,3687726.000,0.560,175.000,1031817.000,742995.000,1073473.000,102.670,35.000

### Mean, Median, Min. und Max.

In [13]:
# Calculate the mean
mean_arbeitslosigkeit = df_raw['clma_Unemployment rate'].mean()

# Calculate the median
median_arbeitslosigkeit = df_raw['clma_Unemployment rate'].median()

# Get the min
min_arbeitslosigkeit = df_raw['clma_Unemployment rate'].min()

# Get the max
max_arbeitslosigkeit = df_raw['clma_Unemployment rate'].max()

# Print the results
print(f"Mean Arbeitslosigkeit(%): {mean_arbeitslosigkeit}")
print(f"Median Arbeitslosigkeit(%): {median_arbeitslosigkeit}")
print(f"Min. Arbeitslosigkeit(%): {min_arbeitslosigkeit}")
print(f"Max. Arbeitslosigkeit(%): {max_arbeitslosigkeit}")

Mean Arbeitslosigkeit(%): 7.774358974358974
Median Arbeitslosigkeit(%): 7.7
Min. Arbeitslosigkeit(%): 1.83
Max. Arbeitslosigkeit(%): 13.44

In [14]:
# Get index of min and max
idx_min = df_raw['clma_Unemployment rate'].idxmin()
idx_max = df_raw['clma_Unemployment rate'].idxmax()

# Get full rows
row_min = df_raw.loc[idx_min]
row_max = df_raw.loc[idx_max]

# Do something with it
print("Row with min:", row_min["cities"])
print("Row with max:", row_max["cities"])

Row with min: Szeged
Row with max: Marseille (greater city)

## Daten Sortieren

In [15]:
sorted_by_size = df_raw.sort_values(by="cpop1_Population on the 1st of January, total", ascending=False)
sorted_by_size.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
34,Paris (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.000,356.170,3687726.000,0.170,175.000,722207.000,223247.000,NaN,NaN,9.100
24,London,NaN,NaN,NaN,NaN,0.800,0.000,5.500,780.000,36.700,...,NaN,282.790,2507333.000,0.130,112.000,NaN,NaN,NaN,NaN,NaN
27,Madrid (greater city),NaN,NaN,NaN,NaN,38.270,2.400,2.100,5779.000,30.300,...,NaN,396.650,1785501.000,0.150,66.000,NaN,NaN,284.000,51.300,NaN
4,Berlin,5.400,18.600,-0.500,568.100,8.330,0.000,13.500,3356.000,23.000,...,12.600,282.690,1061565.000,0.150,55.000,321219.000,185723.000,1073473.000,63.420,17.300
30,Milano (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,585.180,2086015.000,0.290,102.000,1031817.000,742995.000,312.000,NaN,NaN

## Daten Gruppieren

In [ ]:
demo_cities = pd.DataFrame({
    'Country': ['Germany', 'Germany', 'Germany', 'Italy', 'Italy', 'Italy', 'Spain', 'Spain', 'Spain', 'France'],
    'Region': ['South', 'North', 'East', 'North', 'South', 'North', 'North', 'South', 'East', 'North'],
    'City': ['Munich', 'Hamburg', 'Berlin', 'Milan', 'Naples', 'Turin','Bilbao', 'Seville', 'Valencia', 'Paris'],
    'Population': [1487000, 1787000, 3769000, 1377000, 960000, 870000,347000, 690000, 790000, 2161000]
})

demo_cities

   Country Region      City  Population
0  Germany  South    Munich     1487000
1  Germany  North   Hamburg     1787000
2  Germany   East    Berlin     3769000
3    Italy  North     Milan     1377000
4    Italy  South    Naples      960000
5    Italy  North     Turin      870000
6    Spain  North    Bilbao      347000
7    Spain  South   Seville      690000
8    Spain   East  Valencia      790000
9   France  North     Paris     2161000

In [32]:
# Average population by country
grouped = demo_cities.groupby('Country')['Population'].mean()

grouped

Country
France    2161000.000
Germany   2347666.667
Italy     1069000.000
Spain      609000.000
Name: Population, dtype: float64

In [33]:
grouped2 = demo_cities.groupby(['Country', 'Region'])['Population'].sum()
grouped2

Country  Region
France   North     2161000
Germany  East      3769000
         North     1787000
         South     1487000
Italy    North     2247000
         South      960000
Spain    East       790000
         North      347000
         South      690000
Name: Population, dtype: int64

In [34]:
# Count how many cities per country
city_count = demo_cities['Country'].value_counts()
city_count

Country
Germany    3
Italy      3
Spain      3
France     1
Name: count, dtype: int64

## Daten Filtern & Subsets erstellen

Bei der Erstellung eines Subsets geht es darum sowohl Zeilen (cities) wie Spalten (indicators) zu reduzieren.

### Random Sample

In [16]:
# generate a random sample of countries
random_subset = df_raw.sample(n=5, random_state=42)
random_subset

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
13,Geneva (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.200,380.550,164293.000,0.210,9.000,47647.220,15544.680,NaN,73.000,23.000
45,Wien (greater city),NaN,NaN,NaN,NaN,24.600,0.000,20.000,4775.000,20.800,...,NaN,NaN,NaN,0.120,21.000,NaN,NaN,NaN,NaN,NaN
47,Zurich (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.280,407.990,294192.000,0.260,19.000,238202.430,62484.900,NaN,91.000,35.000
44,Warszawa,7.000,21.100,-1.000,519.000,9.000,0.000,40.500,3312.000,24.300,...,NaN,845.970,1574854.000,0.160,29.000,NaN,NaN,773.400,24.400,4.470
17,Hamburg,4.500,17.200,1.400,715.800,3.500,0.000,6.600,2576.000,22.700,...,11.900,341.230,645645.000,0.210,39.000,354483.000,129424.000,652197.000,89.500,15.900

### Filtern nach Werten

In [17]:
# filtering for an absolute value
# != > not equal, == > equal
high_unem = df_raw.copy()

high_unem = high_unem[high_unem['clma_Unemployment rate'] >= mean_arbeitslosigkeit]
high_unem = high_unem.sort_values(by='clma_Unemployment rate', ascending=False)
high_unem.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
29,Marseille (greater city),NaN,NaN,NaN,NaN,20.000,0.000,22.000,4853.000,33.000,...,19.000,427.170,417126.000,0.340,33.000,84252.000,48594.000,NaN,NaN,13.250
32,Napoli (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,644.580,1922891.000,0.340,100.000,470183.000,457396.000,19.200,NaN,NaN
13,Geneva (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.200,380.550,164293.000,0.210,9.000,47647.220,15544.680,NaN,73.000,23.000
33,Ostrava,NaN,NaN,NaN,NaN,23.000,0.000,84.000,4314.000,21.700,...,NaN,378.480,113400.000,0.310,9.000,35663.000,8339.000,79.000,18.010,6.160
45,Wien (greater city),NaN,NaN,NaN,NaN,24.600,0.000,20.000,4775.000,20.800,...,NaN,NaN,NaN,0.120,21.000,NaN,NaN,NaN,NaN,NaN

### Filtern nach Liste

In [18]:
# erstelle eine Kopie um auf das Original zurückgreifen zu können
df = df_raw.copy()
city_selection = [ "Berlin", "Paris (greater city)", "Budapest (greater city)", "Ljubljana", "Bruxelles/Brussel (greater city)"]

df = df[df["cities"].isin(city_selection)]
df.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
4,Berlin,5.400,18.600,-0.500,568.100,8.330,0.000,13.500,3356.000,23.000,...,12.600,282.690,1061565.000,0.150,55.000,321219.000,185723.000,1073473.000,63.420,17.300
8,Bruxelles/Brussel (greater city),5.000,17.600,4.000,815.700,10.330,1.250,14.700,2390.000,30.300,...,NaN,394.550,498855.000,0.090,11.000,NaN,NaN,513.000,60.000,15.000
9,Budapest (greater city),NaN,23.900,-1.000,815.200,21.000,0.000,26.000,3973.000,23.400,...,NaN,428.990,723372.000,0.230,38.000,NaN,NaN,213.000,22.650,7.590
23,Ljubljana,NaN,NaN,NaN,NaN,29.000,0.000,23.000,5528.000,28.500,...,26.490,546.430,162605.000,0.070,2.000,NaN,NaN,362.000,37.000,6.200
34,Paris (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.000,356.170,3687726.000,0.170,175.000,722207.000,223247.000,NaN,NaN,9.100

In [19]:
col_selection = [
    "cities",
    "cpop1_Population on the 1st of January, total",
    "clma_Persons unemployed, total",
    "cpopcb_Nationals",
    "cpopcb_EU foreigners",
    "cpopcb_Non-EU foreigners"
    ]

df = df[col_selection]
df.head()

,cities,"cpop1_Population on the 1st of January, total","clma_Persons unemployed, total",cpopcb_Nationals,cpopcb_EU foreigners,cpopcb_Non-EU foreigners
4,Berlin,3685265.000,138000.000,2856188.000,247600.000,494400.000
8,Bruxelles/Brussel (greater city),1264371.000,68381.000,785550.000,288959.000,189862.000
9,Budapest (greater city),1686222.000,20811.000,1572258.000,23540.000,90424.000
23,Ljubljana,297575.000,7669.000,256288.000,3778.000,37509.000
34,Paris (greater city),10353710.000,609212.000,8609019.000,398598.000,1346093.000

### Filter Cheatsheet

#### Comparison Operators

| Operator | Meaning | Example |
|----------|---------|---------|
| `==` | Equal to | `df[df['col'] == 5]` |
| `!=` | Not equal to | `df[df['col'] != 'A']` |
| `>` | Greater than | `df[df['price'] > 100]` |
| `<` | Less than | `df[df['age'] < 30]` |
| `>=` | Greater than or equal | `df[df['score'] >= 90]` |
| `<=` | Less than or equal | `df[df['temp'] <= 0]` |

#### Logical Operators (combining conditions)

| Operator | Meaning | Example |
|----------|---------|---------|
| `&` | AND | `df[(df['a'] > 1) & (df['b'] < 5)]` |
| `\|` | OR | `df[(df['x'] == 'A') \| (df['y'] == 'B')]` |
| `~` | NOT | `df[~(df['status'] == 'inactive')]` |

#### Membership Operators

| Operator | Meaning | Example |
|----------|---------|---------|
| `.isin()` | Value in list | `df[df['col'].isin(['A', 'B', 'C'])]` |
| `.between()` | In range | `df[df['age'].between(18, 35)]` |

#### String Operators (via `.str` accessor)

```python
df[df['name'].str.contains('test')]    # substring match
df[df['name'].str.startswith('A')]     # starts with
df[df['name'].str.endswith('z')]       # ends with

Key Notes
- Each comparison produces a boolean Series (True/False per row).
- Use parentheses around each condition when combining with & or |.
- Use & and |, not and/or (those don't work element-wise).
- ~ is the bitwise NOT — use it instead of not for negation.

## Export

In [20]:
df.to_excel('./export/subset.xlsx', index=False)

## Missing Data

Often data is sparse so understanding were the data coverage is better/worse helps to decide on what aspect to focus on.

In [21]:
# radical approach, drop all rows/columns with missing data
only_complete = df_raw.dropna()
only_complete.head()

Empty DataFrame
Columns: [cities, cenv_Total number of hours of sunshine per day, cenv_Average temperature of warmest month - degrees, cenv_Average temperature of coldest month - degrees, cenv_Rainfall - litre/m², cenv_Number of days ozone O3 concentrations exceed 120 µg/m³, cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³, cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³, cenv_Accumulated ozone concentration in excess 70 µg/m³, cenv_Annual average concentration of NO2 (µg/m³), cenv_Annual average concentration of PM10 (µg/m³), cenv_Total use of water - m³, cenv_Price of a m³ of domestic water - Euro, cenv_Share of the urban wastewater load (in population equivalents) treated according to the applicable standard -%, cenv_Share of population connected to potable drinking water system - %, cenv_Share of population connected to sewerage treatment system - %, cenv_Municipal waste generated (domestic and commercial), total - 1000 t, cenv_Share of land (%): continuous residential urban fabric, cenv_Share of land (%): discontinuous residential urban fabric, cenv_Share of land (%): industrial, commercial, public, military and private units, cenv_Share of land (%): transport infrastructure, cenv_Share of land (%): other artificial areas, cenv_Share of land (%): green urban areas and sports and leisure facilities, cenv_Share of land (%): agricultural areas, cenv_Share of land (%): natural areas, clivcon_Private households (excluding institutional households), clivcon_Proportion of households that are 1-person households, clivcon_One person households, clivcon_Average size of households, clivcon_Proportion of households that are lone-parent households, clivcon_Lone parent private households (with children aged 0 to under 18), clivcon_Proportion of households that are lone-pensioner households, clivcon_Lone pensioner (above retirement age) households, clivcon_Proportion of households with children aged 0-17, clivcon_Households with children aged 0 to under 18, clivcon_Lone parent households per 100 households with children aged 0-17, clivcon_Population living in private households (excluding institutional households), clivcon_Median disposable annual household income - EUR, clivcon_Average disposable annual household income - EUR, clivcon_Share of persons living in households with very low work intensity - %, clivcon_Share of persons at risk of poverty after social transfers -%, clivcon_Share of severely materially deprived persons -%, clivcon_Share of persons at risk of poverty or social exclusion -%, clivcon_Number of conventional dwellings, clivcon_Number of houses, clivcon_Number of apartments, clivcon_Proportion of households living in houses, clivcon_Number of households living in houses, clivcon_Proportion of households living in apartments, clivcon_Number of households living in apartments, clivcon_Proportion of households living in owned dwellings, clivcon_Households owning their own dwelling, clivcon_Households in social housing, clivcon_Households in private rented housing, clivcon_Dwellings lacking basic amenities, clivcon_Average area of living accommodation - m²/person, clivcon_Empty conventional dwellings, clivcon_Number of people in accommodation for the homeless, clivcon_Average annual rent for housing per m² - EUR, clivcon_Average price for buying a house - EUR, clivcon_Average price for buying an apartment - EUR, clivcon_Average price for buying a house per m2 - EUR, clivcon_Average price for buying an apartment per m2 - EUR, clivcon_Number of murders and violent deaths, clma_Activity rate, clma_Activity rate, male, clma_Economically active population, male, clma_Activity rate, female, clma_Economically active population, female, clma_Persons unemployed, total, clma_Unemployment rate, male, clma_Persons unemployed, male, clma_Unemployment rate, female, clma_Persons unemployed, female, clma_Unemployment rate, clma_Economically active population, 55-64, total, clma_Economically active population, 55-64, male, clma_Economically active population, 55-64, female, clma_Economically active population, 20-64, total, clma_Economically active population, 20-64, male, clma_Economically active population, 20-64, female, clma_Persons employed, 20-64, total, clma_Persons employed, 20-64, male, clma_Persons employed, 20-64, female, clma_Persons employed, 55-64, total, clma_Persons employed, 55-64, male, clma_Persons employed, 55-64, female, clma_Employment (jobs) in agriculture, fishery (NACE Rev. 2, A), clma_Employment (jobs) in mining, manufacturing, energy (NACE Rev. 2, B-E), clma_Total employment/jobs (workplace based), clma_Employment (jobs) in construction (NACE Rev. 2, F), clma_Employment (jobs) in trade, transport, hotels, restaurants (NACE Rev. 2, G to I), clma_Employment (jobs) in information and communication (NACE Rev. 2, J), clma_Employment (jobs) in financial and insurance activities (NACE Rev. 2, K), clma_Employment (jobs) in real estate activities (NACE Rev. 2, L), clma_Employment (jobs) in professional, scientific and technical activities; administrative and support service activities (NACE Rev. 2, M and N), clma_Employment (jobs) in public administration, defence, education, human health and social work activities (NACE Rev. 2, O to Q), clma_Employment (jobs) in arts, entertainment and recreation; other service activities; activities of household and extra-territorial organizations and bodies (NACE Rev. 2, R to T), cpop1_Population on the 1st of January, total, cpop1_Population on the 1st of January, male, ...]
Index: []

[0 rows x 149 columns]

Add a threshold of how many at least must be filled. 
These are the cities were from 149 possible values, 2/3 are available, not so bad..

In [22]:
print("columns: ", len(df_raw.columns))
atleast = df_raw.dropna(thresh=100)

atleast.head()

columns:  149

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.500,0.000,3.500,1917.000,22.400,...,NaN,303.160,325509.000,0.160,16.000,262103.000,98218.000,1154.400,NaN,NaN
1,Antwerpen (greater city),5.000,17.600,4.200,759.800,NaN,0.000,19.000,NaN,28.400,...,NaN,401.430,219900.000,0.160,9.000,NaN,NaN,575.800,49.000,15.000
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.850,387.230,136770.000,0.200,7.000,48180.450,23183.990,NaN,90.000,28.000
4,Berlin,5.400,18.600,-0.500,568.100,8.330,0.000,13.500,3356.000,23.000,...,12.600,282.690,1061565.000,0.150,55.000,321219.000,185723.000,1073473.000,63.420,17.300
5,Birmingham,NaN,NaN,NaN,NaN,3.500,0.000,7.000,1716.000,31.900,...,NaN,330.570,376607.000,0.120,14.000,NaN,NaN,233.000,102.670,NaN

A more sophisticated approach calculates which cities or indicators have the best coverage. This can be done in three steps: 

- `notna()` creates a boolean DataFrame: True where a cell has a value, False where it's missing.
- `.sum(axis=1)` sums across each row or column (axis=1 = rows, axis=0 = columns), counting how many True values each city or indicator has.
- `.sort_values(ascending=False)` — sorts from most to fewest filled.
- because the df returns the first row, which is the index row, the city names are no longer visible. This can be changed using `.set_index("cities")`

In [23]:
print("row count:", len(df_raw))
indicator_coverage = df_raw.notna().sum(axis=0).sort_values(ascending=False)
indicator_coverage.head()

row count: 49

cities                                                                                  49
cpop1_Population on the 1st of January, total                                           49
cpop1_Population on the 1st of January, male                                            49
clivcon_Population living in private households (excluding institutional households)    48
cpopcb_Foreign-born                                                                     48
dtype: int64

In [24]:
print("column count:", len(df_raw.columns))
city_coverage = df_raw.set_index("cities").notna().sum(axis=1).sort_values(ascending=False)
city_coverage.head()

column count: 149

cities
Berlin                  144
Hamburg                 144
München                 144
Lyon (greater city)     133
Paris (greater city)    127
dtype: int64

### Aufgabe: Notes on Data Coverage

Take some minutes to hold a few observations: Which cities have best, worst or average coverage? Which indicators are well covered and what analysis are possible? Formulate at least one data research question to be explored.