# Introduction to Data Preparation with Pandas

Im Rahmen von Think 3 bereiten wir die Daten so auf, dass sie sich für die Visuelle Analyse eignen. D.h. wir rechnen Werte teils so um, dass sie sich für die Visualisierung eignen.

## Setup

In [1]:
import pandas as pd

In [2]:
df_raw = pd.read_csv("data/eurostat_european_cities.csv")
df_raw.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
0,Amsterdam (greater city),NaN,NaN,NaN,NaN,2.50,0.0,3.5,1917.0,22.4,...,NaN,303.16,325509.0,0.16,16.0,262103.00,98218.00,1154.4,NaN,NaN
1,Antwerpen (greater city),5.0,17.6,4.2,759.8,NaN,0.0,19.0,NaN,28.4,...,NaN,401.43,219900.0,0.16,9.0,NaN,NaN,575.8,49.00,15.0
2,Barcelona (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,278.97,741737.0,0.16,42.0,NaN,NaN,NaN,NaN,NaN
3,Basel (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.85,387.23,136770.0,0.20,7.0,48180.45,23183.99,NaN,90.00,28.0
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.0,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.00,185723.00,1073473.0,63.42,17.3

## Subset Erstellen

In [3]:
# erstelle eine Kopie um auf das Original zurückgreifen zu können
df = df_raw.copy()
city_selection = [ "Berlin", "Paris (greater city)", "Budapest (greater city)", "Ljubljana", "Bruxelles/Brussel (greater city)"]

df = df[df["cities"].isin(city_selection)]
df.head()

,cities,cenv_Total number of hours of sunshine per day,cenv_Average temperature of warmest month - degrees,cenv_Average temperature of coldest month - degrees,cenv_Rainfall - litre/m²,cenv_Number of days ozone O3 concentrations exceed 120 µg/m³,cenv_Number of hours nitrogen dioxide NO2 concentrations exceed 200 µg/m³,cenv_Number of days particulate matter PM10 concentrations exceed 50 µg/m³,cenv_Accumulated ozone concentration in excess 70 µg/m³,cenv_Annual average concentration of NO2 (µg/m³),...,ctran_Average length of journey to work by private car - km,ctran_Number of registered cars per 1000 population,ctran_Number of private cars registered,ctran_People killed in road accidents per 10000 pop.,ctran_Number of deaths in road accidents,ctran_People commuting into the city,ctran_People commuting out of the city,ctran_Length of bicycle network (dedicated cycle paths and lanes) - km,ctran_Cost of a combined monthly ticket (all modes of public transport) for 5-10 km in the central zone - EUR,ctran_Cost of a taxi ride of 5 km to the centre at day time - EUR
4,Berlin,5.4,18.6,-0.5,568.1,8.33,0.00,13.5,3356.0,23.0,...,12.60,282.69,1061565.0,0.15,55.0,321219.0,185723.0,1073473.0,63.42,17.30
8,Bruxelles/Brussel (greater city),5.0,17.6,4.0,815.7,10.33,1.25,14.7,2390.0,30.3,...,NaN,394.55,498855.0,0.09,11.0,NaN,NaN,513.0,60.00,15.00
9,Budapest (greater city),NaN,23.9,-1.0,815.2,21.00,0.00,26.0,3973.0,23.4,...,NaN,428.99,723372.0,0.23,38.0,NaN,NaN,213.0,22.65,7.59
23,Ljubljana,NaN,NaN,NaN,NaN,29.00,0.00,23.0,5528.0,28.5,...,26.49,546.43,162605.0,0.07,2.0,NaN,NaN,362.0,37.00,6.20
34,Paris (greater city),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.00,356.17,3687726.0,0.17,175.0,722207.0,223247.0,NaN,NaN,9.10

In [4]:
col_selection = [
    "cities",
    "cpop1_Population on the 1st of January, total",
    "clma_Persons unemployed, total",
    "cpopcb_Nationals",
    "cpopcb_EU foreigners",
    "cpopcb_Non-EU foreigners"
    ]

df = df[col_selection]
df.head()

,cities,"cpop1_Population on the 1st of January, total","clma_Persons unemployed, total",cpopcb_Nationals,cpopcb_EU foreigners,cpopcb_Non-EU foreigners
4,Berlin,3685265.0,138000.0,2856188.0,247600.0,494400.0
8,Bruxelles/Brussel (greater city),1264371.0,68381.0,785550.0,288959.0,189862.0
9,Budapest (greater city),1686222.0,20811.0,1572258.0,23540.0,90424.0
23,Ljubljana,297575.0,7669.0,256288.0,3778.0,37509.0
34,Paris (greater city),10353710.0,609212.0,8609019.0,398598.0,1346093.0

## Spalten ersetzen oder hinzufügen

Um eine neue Spalte hinzu zufügen kann `insert()` genutzt werden wo drei Argumente mitgegeben werden müssen: Position, Name und Inhalt der Spalte.

In [5]:
df_ex1 = df.copy()

df_ex1.insert(
    df_ex1.columns.get_loc("cpopcb_Nationals"), # index position
    "cpopcb_Nationals scaled by 10'000",
    (df_ex1["cpopcb_Nationals"] / 10000).round(0)
)

df_ex1.head()

,cities,"cpop1_Population on the 1st of January, total","clma_Persons unemployed, total",cpopcb_Nationals scaled by 10'000,cpopcb_Nationals,cpopcb_EU foreigners,cpopcb_Non-EU foreigners
4,Berlin,3685265.0,138000.0,286.0,2856188.0,247600.0,494400.0
8,Bruxelles/Brussel (greater city),1264371.0,68381.0,79.0,785550.0,288959.0,189862.0
9,Budapest (greater city),1686222.0,20811.0,157.0,1572258.0,23540.0,90424.0
23,Ljubljana,297575.0,7669.0,26.0,256288.0,3778.0,37509.0
34,Paris (greater city),10353710.0,609212.0,861.0,8609019.0,398598.0,1346093.0

Um eine Spalte mit neuen Werten zu füllen und ihren namen zu ändern kann `rename()` verwendet werden.

In [6]:
df_ex2 = df.copy()

# Werte überschreiben
df_ex2["cpopcb_Nationals"] = (df_ex2["cpopcb_Nationals"]/10000).round(0)

# Umbenennen
df_ex2.rename(columns={"cpopcb_Nationals":"cpopcb_Nationals scaled by 10'000"}, inplace=True)

df_ex2.head()

,cities,"cpop1_Population on the 1st of January, total","clma_Persons unemployed, total",cpopcb_Nationals scaled by 10'000,cpopcb_EU foreigners,cpopcb_Non-EU foreigners
4,Berlin,3685265.0,138000.0,286.0,247600.0,494400.0
8,Bruxelles/Brussel (greater city),1264371.0,68381.0,79.0,288959.0,189862.0
9,Budapest (greater city),1686222.0,20811.0,157.0,23540.0,90424.0
23,Ljubljana,297575.0,7669.0,26.0,3778.0,37509.0
34,Paris (greater city),10353710.0,609212.0,861.0,398598.0,1346093.0

## Datenaufbereitung & Werte berechnen

### Summe und Mittelwerte hinzufügen

Mittels `.loc[]` können zusätzliche Zeilen hinzugefügt werden deren Index anstelle einer Nummer ein Name ist (bspw. "sum"). Das Selbe kann auch für Durschnittswerte gemacht werden. Damit die Werte dieser neuen Zeilen einander nicht beeinflussen müssen sie getrennt berechnet werden.

In [7]:
df_sum = df.copy()
df_avg = df.copy()

df_sum.loc["sum"] = df_sum.sum(numeric_only=True)
df_sum.loc["avg"] = df_avg.mean(numeric_only=True).round(2)

df_sum.head(10)

,cities,"cpop1_Population on the 1st of January, total","clma_Persons unemployed, total",cpopcb_Nationals,cpopcb_EU foreigners,cpopcb_Non-EU foreigners
4,Berlin,3685265.0,138000.0,2856188.0,247600.0,494400.0
8,Bruxelles/Brussel (greater city),1264371.0,68381.0,785550.0,288959.0,189862.0
9,Budapest (greater city),1686222.0,20811.0,1572258.0,23540.0,90424.0
23,Ljubljana,297575.0,7669.0,256288.0,3778.0,37509.0
34,Paris (greater city),10353710.0,609212.0,8609019.0,398598.0,1346093.0
sum,NaN,17287143.0,844073.0,14079303.0,962475.0,2158288.0
avg,NaN,3457428.6,168814.6,2815860.6,192495.0,431657.6

### Werte Skalieren

Für die Visualisierung ist es manchmal hilfreich wenn die Werte um einen bestimmten Faktor skaliert sind, so dass die Verhältnisse besser in visuelle Mittel wir Grösse, Position oder Farbe übersetzbar sind. 

Dazu kann `insert()` genutzt werden wo drei Argumente mitgegeben werden müssen: Position, Name und Inhalt der Spalte.

In [8]:
df_scaled = df.copy()

# Population
df_scaled["cpop1_Population on the 1st of January, total"] = (df_scaled["cpop1_Population on the 1st of January, total"]/10000).round(0)
df_scaled.rename(columns={"cpop1_Population on the 1st of January, total":"cpop1_Population on the 1st of January, total scaled by 10'000"}, inplace=True)

# Employment
df_scaled["clma_Persons unemployed, total"] = (df_scaled["clma_Persons unemployed, total"]/10000).round(0)
df_scaled.rename(columns={"clma_Persons unemployed, total":"clma_Persons unemployed, total scaled by 10'000"}, inplace=True)

# Nationals
df_scaled["cpopcb_Nationals"] = (df_scaled["cpopcb_Nationals"]/10000).round(0)
df_scaled.rename(columns={"cpopcb_Nationals":"cpopcb_Nationals, total scaled by 10'000"}, inplace=True)

# Übung: Wiederhole das ganze für cpopcb_EU foreigners und cpopcb_Non-EU foreigners

# Foreigners
df_scaled["cpopcb_EU foreigners"] = (df_scaled["cpopcb_EU foreigners"]/10000).round(0)
df_scaled.rename(columns={"cpopcb_EU foreigners":"cpopcb_EU foreigners, total scaled by 10'000"}, inplace=True)

# Non-EU Foreigners
df_scaled["cpopcb_Non-EU foreigners"] = (df_scaled["cpopcb_Non-EU foreigners"]/10000).round(0)
df_scaled.rename(columns={"cpopcb_Non-EU foreigners":"cpopcb_Non-EU foreigners, total scaled by 10'000"}, inplace=True)

df_scaled.head()

,cities,"cpop1_Population on the 1st of January, total scaled by 10'000","clma_Persons unemployed, total scaled by 10'000","cpopcb_Nationals, total scaled by 10'000","cpopcb_EU foreigners, total scaled by 10'000","cpopcb_Non-EU foreigners, total scaled by 10'000"
4,Berlin,369.0,14.0,286.0,25.0,49.0
8,Bruxelles/Brussel (greater city),126.0,7.0,79.0,29.0,19.0
9,Budapest (greater city),169.0,2.0,157.0,2.0,9.0
23,Ljubljana,30.0,1.0,26.0,0.0,4.0
34,Paris (greater city),1035.0,61.0,861.0,40.0,135.0

### Prozente Berechnen

population_share = (population / sum(all population)) * 100

In [9]:
df_perc = df.copy()

# Population
df_perc["cpop1_Population on the 1st of January, total"] = (
    df_perc["cpop1_Population on the 1st of January, total"] /
    df_perc["cpop1_Population on the 1st of January, total"].sum()*100
    ).round(0)

df_perc.rename(columns={"cpop1_Population on the 1st of January, total":
    "cpop1_Population on the 1st of January, total in %"}, inplace=True)


# Unemployment
df_perc["clma_Persons unemployed, total"] = (
    df_perc["clma_Persons unemployed, total"] /
    df_perc["clma_Persons unemployed, total"].sum()*100
    ).round(0)

df_perc.rename(columns={"clma_Persons unemployed, total":
    "clma_Persons unemployed, total in %"}, inplace=True)

# Nationals
df_perc["cpopcb_Nationals"] = (
    df_perc["cpopcb_Nationals"] /
    df_perc["cpopcb_Nationals"].sum()*100
    ).round(0)

df_perc.rename(columns={"cpopcb_Nationals":
    "cpopcb_Nationals in %"}, inplace=True)

# EU Foreigners
df_perc["cpopcb_EU foreigners"] = (
    df_perc["cpopcb_EU foreigners"] /
    df_perc["cpopcb_EU foreigners"].sum()*100
    ).round(0)

df_perc.rename(columns={"cpopcb_EU foreigners":
    "cpopcb_EU foreigners in %"}, inplace=True)

# Non-EU Foreigners
df_perc["cpopcb_Non-EU foreigners"] = (
    df_perc["cpopcb_Non-EU foreigners"] /
    df_perc["cpopcb_Non-EU foreigners"].sum()*100
    ).round(0)

df_perc.rename(columns={"cpopcb_Non-EU foreigners":
    "cpopcb_Non-EU foreigners in %"}, inplace=True)


df_perc.head(10)

,cities,"cpop1_Population on the 1st of January, total in %","clma_Persons unemployed, total in %",cpopcb_Nationals in %,cpopcb_EU foreigners in %,cpopcb_Non-EU foreigners in %
4,Berlin,21.0,16.0,20.0,26.0,23.0
8,Bruxelles/Brussel (greater city),7.0,8.0,6.0,30.0,9.0
9,Budapest (greater city),10.0,2.0,11.0,2.0,4.0
23,Ljubljana,2.0,1.0,2.0,0.0,2.0
34,Paris (greater city),60.0,72.0,61.0,41.0,62.0

### Abweichung zum Mittelwert berechnen

In [10]:
# Wir verwenden hierfür die Prozente anstelle der absoluten Zahlen
df_diff = df_perc.copy()

# using a for loop for faster calculations
for col in df_diff.columns:
    
    if col != 'cities':
        # werte berechnen
        df_diff[col] = (df_diff[col] - df_diff[col].mean()).round(2)
        # umbenennen
        new_name = col + ' Difference %'
        df_diff.rename(columns={col : new_name}, inplace=True)
        
df_diff.head(10)

,cities,"cpop1_Population on the 1st of January, total in % Difference %","clma_Persons unemployed, total in % Difference %",cpopcb_Nationals in % Difference %,cpopcb_EU foreigners in % Difference %,cpopcb_Non-EU foreigners in % Difference %
4,Berlin,1.0,-3.8,0.0,6.2,3.0
8,Bruxelles/Brussel (greater city),-13.0,-11.8,-14.0,10.2,-11.0
9,Budapest (greater city),-10.0,-17.8,-9.0,-17.8,-16.0
23,Ljubljana,-18.0,-18.8,-18.0,-19.8,-18.0
34,Paris (greater city),40.0,52.2,41.0,21.2,42.0

### Kategorien bilden

Durch die Anwendung von Schwellenwerten oder Bereichen, die auf dem Wertebereich der jeweiligen Spalte basieren, können Kategorien gebildet werden. Das Ziel ist es, aus den kontinuierlichen Werten diskrete Kategorien zu schaffen, die für die Visualisierung und die spätere Arbeit mit MID besser handhabbar sind. 

Wir können dazu die Funktion `cut` aus [Pandas nutzen](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html).

In [11]:
df_cat = df.copy()

# create three bins of equal size
bins = 3
labels = ["small", "medium", "large"]

for col in df_cat.columns:
    if col != 'cities':
        # werte berechnen
        df_cat[col] = pd.cut(df_cat[col], bins=bins, labels=labels)
        # umbenennen
        new_name = col + ' cat'
        df_cat.rename(columns={col : new_name}, inplace=True)
        
df_cat.head(10)

,cities,"cpop1_Population on the 1st of January, total cat","clma_Persons unemployed, total cat",cpopcb_Nationals cat,cpopcb_EU foreigners cat,cpopcb_Non-EU foreigners cat
4,Berlin,medium,small,small,medium,medium
8,Bruxelles/Brussel (greater city),small,small,small,large,small
9,Budapest (greater city),small,small,small,small,small
23,Ljubljana,small,small,small,small,small
34,Paris (greater city),large,large,large,large,large

## Export

In [12]:
df_sum.to_excel("./export/df_sum.xlsx", index=False)
df_scaled.to_excel("./export/df_scaled.xlsx", index=False)
df_perc.to_excel("./export/df_perc.xlsx", index=False)
df_diff.to_excel("./export/df_diff.xlsx", index=False)
df_cat.to_excel("./export/df_cat.xlsx", index=False)